### ISSUE TITLE
A error happened when I run  generate_tfrecords.sh

### ISSUE THREAD

**Issue by HuGanghui** [floft/codats#1]
Hello, I am a student interested in Deep Domain Adaptation for Time-Series. I am trying to run your code, but I have encountered some problems, I hope to get your help.

**my local machine : MacOS**

I setup environments (CPU version) and download necessary packages according to Installation in README.md, and then I try to run generate_tfrecords.sh, an error happened:

```
"""
Traceback (most recent call last):
  File "/Users/hgh/miniconda3/envs/codats-cpu/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/main.py", line 95, in save_dataset
    dataset, dataset_class = datasets.load(dataset_name)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 1249, in load
    *args, **kwargs)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 58, in call_dataset
    return get_dataset(name)(*args, **kwargs)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 319, in __init__
    None, None, uWaveBase.feature_names, *args, **kwargs)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 131, in __init__
    train_data, train_labels, test_data, test_labels = self.load()
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 421, in load
    x, y = self.load_zip(dataset_fp)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 403, in load_zip
    new_data, new_labels = self.load_rar(io.BytesIO(contents))
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 367, in load_rar
    contents = self.get_file_in_archive(archive, f)
  File "/Users/hgh/Documents/Github_public_algorithm_code/codats/datasets/datasets.py", line 184, in get_file_in_archive
    contents = fp.read()
  File "/Users/hgh/miniconda3/envs/codats-cpu/lib/python3.7/site-packages/rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=3857 got=51
"""
```

I don't know what the problem is. Is it the version of RarFile? The default download is rarFile ==4.0. Or something else?

my full pip list:
```
Package                Version
---------------------- -------------------
absl-py                0.11.0
appnope                0.1.0
argon2-cffi            20.1.0
astor                  0.8.1
async-generator        1.10
attrs                  20.3.0
backcall               0.2.0
bleach                 3.2.1
cached-property        1.5.2
cachetools             4.1.1
certifi                2020.11.8
cffi                   1.14.3
chardet                3.0.4
cycler                 0.10.0
Cython                 0.29.21
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
gast                   0.2.2
google-auth            1.23.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.33.2
h5py                   3.1.0
idna                   2.10
importlib-metadata     3.0.0
ipykernel              5.3.4
ipython                7.19.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.17.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.7.0
jupyterlab-pygments    0.1.2
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
lxml                   4.6.1
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.3.3
mistune                0.8.4
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.3
notebook               6.1.5
numpy                  1.19.4
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.4
pandas                 1.1.4
pandocfilters          1.4.3
parso                  0.7.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.0.1
pip                    20.2.4
prometheus-client      0.9.0
prompt-toolkit         3.0.8
protobuf               3.14.0
ptyprocess             0.6.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.2
pyparsing              2.4.7
pyrsistent             0.17.3
python-dateutil        2.8.1
pytz                   2020.4
PyYAML                 5.3.1
pyzmq                  20.0.0
qtconsole              4.7.7
QtPy                   1.9.0
rarfile                4.0
requests               2.25.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             50.3.1.post20201107
six                    1.15.0
tensorboard            2.1.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.1.0
tensorflow-addons      0.9.1
tensorflow-estimator   2.1.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
threadpoolctl          2.1.0
tornado                6.1
tqdm                   4.53.0
traitlets              5.0.5
typeguard              2.10.0
urllib3                1.26.2
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
wrapt                  1.12.1
zipp                   3.4.0
```

**Comment by HuGanghui** [comment]
I also try it on **Ubuntu 16.04.5 LTS**, also got error. but it is another error:

```
 0%|          | 0/131 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/data/HuGanghui/miniconda3/envs/codats-cpu/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)
```

my full pip list on Ubuntu 16.04.5 LTS

```
Package                Version
---------------------- -------------------
absl-py                0.11.0
argon2-cffi            20.1.0
astor                  0.8.1
astunparse             1.6.3
async-generator        1.10
attrs                  20.3.0
backcall               0.2.0
bleach                 3.2.1
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
cycler                 0.10.0
Cython                 0.29.21
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
gast                   0.2.2
google-auth            1.23.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.33.2
h5py                   2.10.0
idna                   2.10
importlib-metadata     3.0.0
ipykernel              5.3.4
ipython                7.19.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.17.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.7.0
jupyterlab-pygments    0.1.2
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
List                   1.3.0
lxml                   4.6.1
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.3.3
mistune                0.8.4
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.3
notebook               6.1.5
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.4
pandas                 1.1.4
pandocfilters          1.4.3
parso                  0.7.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.0.1
pip                    20.2.4
prometheus-client      0.9.0
prompt-toolkit         3.0.8
protobuf               3.14.0
ptyprocess             0.6.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.2
pyparsing              2.4.7
pyrsistent             0.17.3
python-dateutil        2.8.1
pytz                   2020.4
PyYAML                 5.3.1
pyzmq                  20.0.0
qtconsole              4.7.7
QtPy                   1.9.0
rarfile                4.0
requests               2.25.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             50.3.1.post20201107
six                    1.15.0
tensorboard            2.1.1
tensorboard-plugin-wit 1.7.0
tensorflow             2.1.0
tensorflow-addons      0.9.1
tensorflow-estimator   2.1.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
threadpoolctl          2.1.0
tornado                6.1
tqdm                   4.53.0
traitlets              5.0.5
typeguard              2.10.0
urllib3                1.26.2
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
wrapt                  1.12.1
zipp                   3.4.0
```

**Comment by floft** [comment]
In the second error you posted, it looks like it isn't downloading the datasets due to some certificate errors. You could instead manually create _~/.keras/datasets_ and download each dataset into that directory. The list of files to download are in _datasets/datasets.py_, search for `self.download_dataset(`. For example, the first one is:

    self.download_dataset(["uWaveGestureLibrary.zip"],
            "https://zhen-wang.appspot.com/rice/files/uwave")

So you could download https://zhen-wang.appspot.com/rice/files/uwave/uWaveGestureLibrary.zip manually into _~/.keras/datasets_.

I don't use Mac so I'm not entirely sure about the first error. It looks like I have rarfile 4.0, so I think we're using the same version. I'm guessing maybe a corrupt file? You could try deleting the file in _~/.keras/datasets/_ and downloading it again. Alternatively, if you don't find a way to make rarfile work, you could skip dataset(s) causing issues by commenting out the `@register_dataset("...")` lines of those datasets in _datasets/datasets.py_.
